### PR TITLE
Added openstake.net gentx for testnet-9000

### PR DESCRIPTION
**Pull request by baln2018**
Please review and merge, thanks.

### CODE REVIEW

**Comment by baln2018** [comment]
@karzak Hi Kevin, I can see you've merged other MRs but not mine. Just wondered any issue on my gentx MR or do I need to do something to get merged my gentx? Thanks,

**Comment by baln2018** [comment]
@karzak any reason please why the PR not merged?

**Comment by karzak** [comment]
Nope, my bad, was just rushing. If you want to spin up a node, you're welcome to and I can send some testnet kava to it.

**Comment by baln2018** [comment]
@karzak my node is up now. Can you send some kava, please?

"delegator_address":"kava1san6s5kumm85047hrj8fr4v4g4f5sd2qq07dye"
"validator_address":"kavavaloper1san6s5kumm85047hrj8fr4v4g4f5sd2qdey9uw"

$ kvcli status --output json | jq '.sync_info'
{
  "latest_block_hash": "6F61FB1B26547B2F926D8374B6D9D7F7EB214B1A58E1FC8C32DDD0B3851B7251",
  "latest_app_hash": "420940BA8BE72CF8FA7B017F605B51427C9A3B2BD68844154ED1FBE683D62D5B",
  "latest_block_height": "13670",
  "latest_block_time": "2020-09-01T10:53:30.735094673Z",
  "earliest_block_hash": "02E36D34768465BBD6C6631C84F5FFDABF7DE36A8529B6537027260F6B07A68B",
  "earliest_app_hash": "",
  "earliest_block_height": "1",
  "earliest_block_time": "2020-08-31T14:00:00Z",
  "catching_up": false
}

**Comment by baln2018** [comment]
@karzak just to remind you to transfer a few kava to the testnet-9000 address ( kava1san6s5kumm85047hrj8fr4v4g4f5sd2qq07dye ) for activating my validator node. Thanks.

**Comment by baln2018** [comment]
Closed this request due to no answer from @karzak

**Comment by JoeKash** [comment]
@baln2018 check your address sent it a few testnet tokens

**Comment by karzak** [comment]
Sent tokens, sorry for slow response @baln2018

**Comment by baln2018** [comment]
@JoeKash Thank you!

**Comment by baln2018** [comment]
@karzak Thank you !

**Pull request closed without merging**
